# ========================
# SERVER CONFIG
# ========================
server.port=${PORT:8082}
spring.application.name=quantity-service

# ========================
# EUREKA CONFIG
# ========================
eureka.client.service-url.defaultZone=https://qma-service-registry.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ========================
# DB CONFIG (ENV)
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ========================
# JPA CONFIG
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ========================
# LOGGING (OPTIONAL)
# ========================
logging.level.org.springframework=INFO